const Product = () => {
	return <div>
		<p>salam product1</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
		<p>salam product</p>
	</div>;
};

export default Product;
